### ISSUE TITLE
tusd doesn't get or respect environment variables

### ISSUE THREAD

**Issue by mkabatek** [tus/tusd#1171]
**Question**

Hello I'm using docker compose to run a TUS server using `tusd` The only way I can get the parameters to configure the server is by passing them via `command`:

```
  tus:
    image: tusproject/tusd
    command: -verbose -s3-bucket fieldsync-files-dev -s3-endpoint http://localhost:4566 -port 1080 -host localhost
    ports:
      - "127.0.0.1:1080:1080"
    networks:
      - ls-net
```

However I'd like to configure the server using environment variables. So I have two questions: 

1. Where can I find an exhaustive list of environment variables used by `tusd` I've been trying to look through the source, but I don't see these in the source or docs. https://tus.github.io/tusd/getting-started/installation/#docker-container

2. Ideally I'd like to pass configuration parameters using environment variables in the way I do for `uppy` however none of the following work, while they do work for uppy companion:

## Passing via environment file

```
  tus:
    image: tusproject/tusd
    ports:
      - "127.0.0.1:1080:1080"
    env_file:
      - ./workspaces/backend/.env
    networks:
      - ls-net
```

## Passing via environment

```
  tus:
    image: tusproject/tusd
    ports:
      - "127.0.0.1:1080:1080"
    environment:
      TUS_PORT: 1080
    networks:
      - ls-net
```

## Passing via environment alternative

```
  tus:
    image: tusproject/tusd
    ports:
      - "127.0.0.1:1080:1080"
    environment:
      - "TUS_PORT=1080"
    networks:
      - ls-net
```
