### ISSUE TITLE
pre-finish hook not enabled by default as documented  

### ISSUE THREAD

**Issue by whisper-bye** [tus/tusd#1230]
**Description:**  
The documentation states that the `pre-finish` hook is enabled by default. However, in practice, this hook does not trigger unless the `-hooks-enabled-events=pre-finish` option is explicitly specified.  

Reference: [[tusd documentation - List of available hooks](https://tus.github.io/tusd/advanced-topics/hooks/#list-of-available-hooks)](https://tus.github.io/tusd/advanced-topics/hooks/#list-of-available-hooks)  

**Steps to Reproduce:**  
1. Set up a tusd server without specifying the `-hooks-enabled-events` option.  
2. Add a `pre-finish` hook script to the hooks directory.  
3. Upload a file to the server.  
4. Observe that the `pre-finish` hook is not triggered.  

**Expected Behavior:**  
The `pre-finish` hook should be triggered by default, as mentioned in the documentation.  

**Actual Behavior:**  
The `pre-finish` hook is not triggered unless explicitly enabled with `-hooks-enabled-events=pre-finish`.  

**Environment:**  
- tusd version: docker latest
- Configuration: 
```yaml
  tus:
    image: tusproject/tusd:latest
    ports:
      - '8080:8080'
    volumes:
      - ./tus/srv/tusd-data/data:/srv/tusd-data/data
    command: -hooks-http http://host.docker.internal:8000/v1/write -hooks-enabled-events=pre-finish
    restart: on-failure
```
