### ISSUE TITLE
Files aren't on Minio  tusd using docker-compse

### ISSUE THREAD

**Issue by MortezaAghili** [tus/tusd#408]
**Question**
I'm gonna use **`tusd`** on one of our platforms for uploading big data so, I configured it with docker-compose to work with Minio on a big scale! But there is an issue. I cannot see uploaded files expected on Minio's bucket.  

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: `Linux`
- Used tusd version: `Latest one on docker-hub`
- Used tusd data storage: `s3`
- Used tusd configuration: `command: tusd -s3-bucket uploaded -s3-endpoint http://localhost:9000`
- Used tus client library: `tus-js-client`

Here is my config for these two services:
```
  miniod:
    image: minio/minio:latest
    volumes:
      - miniod:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET}
      MINIO_REGION_NAME: us-east-2
    networks:
      - bluediamond
    command: server data

  tusd:
    image: tusproject/tusd
    volumes:
      - tusd:/data
    ports:
      - "1080:1080"
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET}
      AWS_REGION: us-east-2
    networks:
      - bluediamond
    restart: unless-stopped
    command: tusd -s3-bucket uploaded -s3-endpoint http://localhost:9000

volumes:
  ...
  miniod:
  tusd:

```

also, here is the client result:
![Screenshot from 2020-07-09 19-07-46](https://user-images.githubusercontent.com/6826680/87053724-8f27ad80-c217-11ea-8f6c-80ba6cf13d0b.png)
