### ISSUE TITLE
TUSD behind Traefik 2 reverse proxy

### ISSUE THREAD

**Issue by renepardon** [tus/tusd#625]
**Question**
I can not make the file upload work with TUSD sitting behind Traefik 2. We Upload with Uppy within a create-react-app. TUSD runs on a Docker Swarm cluster. example.com is a replacement for our domain which can be called with HTTPS only.

The error is the folowing:

```bash
Blocked loading mixed active content “http://example.com/files/ec812c10c32ed23b31cf4976fb8af469”
2 httpStack.js:96:19
XHRHEADhttp://example.com/files/ec812c10c32ed23b31cf4976fb8af469
```

The corresponding tusd service in stack.yml looks like:

```yaml
tusd:
    image: tusproject/tusd:v1.8.0
    command: -verbose --hooks-http=http://api:8080/api/uploader/tusd/webhook -hooks-stop-code=401 -hooks-http-backoff=60 -hooks-http-retry=2 -behind-proxy=true
    volumes:
      - "/usr/local/myfolder/files:/srv/tusd-data/data"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.port=1080"
        - "traefik.docker.network=mynetwork"
        - "traefik.http.routers.tusd.rule=Host(`example.com`) && PathPrefix(`/files`)"
        - "traefik.http.routers.tusd.priority=2"
        - "traefik.http.routers.tusd.entrypoints=websecure"
        - "traefik.http.routers.tusd.tls=true"
        - "traefik.http.routers.tusd.tls.certresolver=myprivatesocietey"
        - "traefik.http.routers.tusd.service=tusd-service"
        - "traefik.http.services.tusd-service.loadbalancer.server.port=1080"
        - "traefik.http.middlewares.tusd.headers.customrequestheaders.X-Forwarded-Proto=https"
```

On Traefik itself i configured the following headers:

```
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.passHostHeader=true"
```

`passHostHeader` because the FAQ mentioned the X-Forwarded-* headers should be available.

**Comment by renepardon** [comment]
Ok, was not my fault on server side, was Uppy itself: https://github.com/transloadit/uppy/issues/2285#issuecomment-632920770
This helped. So I had to clear local storage explicitly. Reload without Cache is not enough.

**Comment by ilomon10** [comment]
🎊 Solved with my current setup

```
Browser (HTTPS)
   ↓
Cloudflare Tunnel (HTTPS)
   ↓
Traefik (usually HTTP internally, or HTTPS if configured)
   ↓
tus-server (HTTP, but behind proxy)
```

Just add this config
```yaml
entryPoints:
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true  # ⚠️ Allow trusting forwarded headers from Cloudflare
```

or trust one by one the ips
```yaml
# traefik.yml or traefik.toml
entryPoints:
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "173.245.48.0/20"   # Cloudflare IP ranges
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
```
